version: '3'

services:
  frontend:
    image: https://hub.docker.com/hazemkaroui/frontend:latest
    build:
      context: ./frontend
    ports:
      - "3000:3000"

  backend:
    image: https://hub.docker.com/hazemkaroui/backend:latest
    build:
      context: ./backend
    environment:
      - MONGODB_URI=mongodb://mongo:27017/nicedb
    ports:
      - "4000:4000"
    depends_on:
      - mongo

  mongo:
    image: mongo
    ports:
      - "27017:27017"
